---
cluster:
  name: cluster-two

destinations:
  metricsGateway:
    type: prometheus
    url: http://gateway.default.svc.cluster.local:9090/api/v1/metrics/write
  logsGateway:
    type: loki
    url: http://gateway.default.svc.cluster.local:3500/loki/api/v1/push
  tracesGateway:
    type: otlp
    url: gateway.default.svc.cluster.local:4317
    protocol: grpc
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}
    tls:
      insecure: true
  profilesGateway:
    type: pyroscope
    url: http://gateway.default.svc.cluster.local:4040

clusterMetrics:
  enabled: true

hostMetrics:
  enabled: true
  linuxHosts:
    enabled: true
    source: alloy

clusterEvents:
  enabled: true

podLogsViaLoki:
  enabled: true
  namespaces: [cluster-two]

telemetryServices:
  kube-state-metrics:
    deploy: true

collectors:
  alloy:
    includeDestinations: [metricsGateway, logsGateway, tracesGateway, profilesGateway]
    presets: [clustered, filesystem-log-reader, linux-host-monitor, daemonset]
    extraConfig: |
      // Generate traces
      tracing {
        sampling_fraction = 0.1
        send_traceparent = true
        write_to = [otelcol.processor.attributes.tracesgateway.input]
      }

      // Generate profiles
      pyroscope.scrape "local" {
        targets = [{"__address__" = "localhost:12345", "service_name"="alloy", "service_namespace"="cluster-two"}]
        profiling_config {
          profile.block {
            enabled = false
          }
          profile.goroutine {
            enabled = false
          }
          profile.memory {
            enabled = false
          }
          profile.mutex {
            enabled = false
          }
          profile.process_cpu {
            enabled = true
          }
        }
        forward_to = [pyroscope.write.profilesgateway.receiver]
      }

# Don't create an Alloy Operator, but let the main one create the Alloy instances
# This is only because we're using a single cluster to demonstrate the gateway pattern, rather than discrete clusters.
alloy-operator:
  deploy: false
