---
# -- The value for the job label applied to collected logs.
# @section -- Processing settings
jobLabel: "integrations/kubernetes/manifest-tail"

# -- Pod label selectors used to find the k8s-manifest-tail pods.
# @section -- Processing settings
labelSelectors:
  app.kubernetes.io/name: k8s-manifest-tail

# -- The structured metadata mappings to set.
# Format: `<key>: <extracted_key>`.
# @section -- Processing settings
structuredMetadata: {}

# -- Stage blocks to be added to the loki.process component for Kubernetes manifest logs.
# ([docs](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.process/#blocks))
# This value is templated so that you can refer to other values from this file.
# @section -- Processing settings
extraLogProcessingStages: ""
