---
global:
  # -- Override the namespace for namespaced resources created by this chart.
  # @section -- Global Settings
  namespaceOverride: ""

# -- The value for the job label.
# @section -- General Settings
jobLabel: "integrations/kubernetes/manifests"
