---
cluster:
  name: etcd-integration-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

integrations:
  collector: alloy-metrics
  etcd:
    instances:
      - name: etcd
        labelSelectors:
          app.kubernetes.io/component: etcd

collectors:
  alloy-metrics: {}

