---
cluster:
  name: auto-instrumentation-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

autoInstrumentation:
  enabled: true
  collector: alloy-metrics
  spanMetricsOnly: true

collectors:
  alloy-metrics: {}

