---
# Clustered preset

# -- Enables Alloy clustering to distribute telemetry gathering compatible work across multiple replicas.
# @section -- Alloy Configuration
alloy:
  clustering:
    enabled: true
