---
# DaemonSet preset

# -- Configures Alloy to run as a DaemonSet, ensuring a single instance per node.
# @section -- Alloy Configuration
controller:
  type: daemonset
  tolerations:
    - effect: NoSchedule
      operator: Exists
