---
# Filesystem log reader preset

# -- Configures Alloy to mount the /var/log from the Node's file system.
# @section -- Alloy Configuration
alloy:
  mounts:
    # Mount `/var/log` from the host into the container for log collection.
    varlog: true

    # Also mount `/var/lib/docker/containers` from the host into the container for log collection.
    dockercontainers: true
