---
# Host Cgroup preset

# -- Mounts the host's cgroup filesystem into Alloy, allowing it to read cgroup information for the node.
# @section -- Alloy Configuration
alloy:
  mounts:
    extra:
      - name: cgroup
        mountPath: /sys/fs/cgroup

controller:
  volumes:
    extra:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
