---
# Privileged preset

# -- Configures Alloy to run with elevated privileges, allowing it to access system resources and perform operations
# that require root access.
# @section -- Alloy Configuration
alloy:
  securityContext:
    allowPrivilegeEscalation: true
    privileged: true
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

controller:
  hostPID: true
