---
# Service Discovery preset

# -- Sets the "service-discovery" attribute when using remote configuration, which indicates that this collector
# instance should get cluster service discovery configuration.
# @section -- Alloy Configuration
remoteConfig:
  extraAttributes:
    service-discovery: true
