---
#
# Singleton preset
# Configures Alloy to run as a single-instance, protecting workloads that would result in duplicated data if run on multiple replicas.
#
controller:
  type: deployment
  replicas: 1
