---
# Singleton preset

# -- Configures Alloy to run as a single-instance, protecting workloads that would result in duplicated data if run on
# multiple replicas.
# @section -- Alloy Configuration
controller:
  type: deployment
  replicas: 1
