---
cluster:
  name: openshift-cluster

global:
  platform: openshift

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

  loki:
    type: loki
    url: http://prometheus.prometheus.svc:9090/api/v1/write

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  kube-state-metrics:
    namespace: openshift-monitoring
    labelMatchers:
      app.kubernetes.io/name: kube-state-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
    namespace: openshift-monitoring
    labelMatchers:
      app.kubernetes.io/name: prometheus-node-exporter
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
  energyMetrics:
    enabled: true

telemetryServices:
  kepler:
    deploy: true

clusterEvents:
  enabled: true
  collector: alloy-singleton

podLogs:
  enabled: true
  collector: alloy-logs

integrations:
  collector: alloy-metrics
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name: [alloy-metrics, alloy-singleton, alloy-logs]

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]

  alloy-singleton:
    presets: [singleton]

  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
    global:
      podSecurityContext:
        seLinuxOptions:
          type: container_logreader_t
