---
cluster:
  name: multiline-pod-logs

destinations:
  loki:
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push
    tenantId: 1
    auth:
      type: basic
      username: loki
      password: lokipassword

podLogs:
  enabled: true
  collector: alloy-logs
  extraLogProcessingStages: |
    stage.match {
      selector = "{app_kubernetes_io_name=\"multiline-pod\"}"
      stage.multiline {
        firstline = "^level=[A-Z]+"
      }
    }

collectors:
  alloy-logs: {}

