---
cluster:
  name: host-metrics-example-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

hostMetrics:
  enabled: true
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true
  energyMetrics:
    enabled: true

collectors:
  alloy-metrics:
    presets: [medium, clustered, statefulset]

telemetryServices:
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
  kepler:
    deploy: true
