---
global:
  # -- Override the namespace for namespaced resources created by this chart.
  # @section -- Global Settings
  namespaceOverride: ""

# -- Only capture logs from pods in these namespaces (`[]` means all namespaces).
# @section -- Pod Discovery
namespaces: []

# -- Do not capture logs from any pods in these namespaces.
# @section -- Pod Discovery
excludeNamespaces: []

# -- Log attributes to set with values copied from the Kubernetes Pod labels.
# Format: `<log_label>: <kubernetes_label>`.
# @section -- Log Processing
labels:
  app_kubernetes_io_name: app.kubernetes.io/name

# -- Log attributes to set with values copied from the Kubernetes Node labels.
# Format: `<log_label>: <kubernetes_node_label>`.
# @section -- Log Processing
nodeLabels: {}

# -- Log attributes to set with values copied from the Kubernetes Namespace labels.
# Format: `<log_label>: <kubernetes_namespace_label>`.
# @section -- Log Processing
namespaceLabels: {}

# -- Log attributes to set with static values.
# @section -- Log Processing
staticAttributes: {}

# -- Log attributes to set with static values, not quoted so it can reference config components.
# @section -- Log Processing
staticAttributesFrom: {}

# -- Log attributes to set with values copied from the Kubernetes Pod annotations.
# Format: `<log_label>: <kubernetes_annotation>`.
# @section -- Log Processing
annotations: {}

# -- Log attributes to set with values copied from the Kubernetes Node annotations.
# Format: `<log_label>: <kubernetes_node_annotation>`.
# @section -- Log Processing
nodeAnnotations: {}

# -- Log attributes to set with values copied from the Kubernetes Namespace annotations.
# Format: `<log_label>: <kubernetes_namespace_annotation>`.
# @section -- Log Processing
namespaceAnnotations: {}

# -- Whether to automatically set the recommended OpenTelemetry
# [resource attributes](https://opentelemetry.io/docs/specs/semconv/non-normative/k8s-attributes/).
# @section -- Log Processing
otelAnnotations: false

# -- Only gather new log lines since this was deployed. Do not gather historical log lines.
# @section -- Volume Log Gathering
onlyGatherNewLogLines: true
