---
cluster:
  name: sharded-kube-state-metrics

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

collectors:
  alloy-metrics: {}

telemetryServices:
  kube-state-metrics:
    deploy: true
    autosharding:
      enabled: true
    replicas: 5
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
