---
cluster:
  name: external-secrets-example-cluster

destinations:
  metrics-service:
    type: prometheus
    urlFrom: convert.nonsensitive(remote.kubernetes.secret.metrics_service.data["prom-host"]) + "/api/v1/write"
    auth:
      type: basic
      usernameKey: prom-username
      passwordKey: access-token
    secret:
      create: false
      name: my-monitoring-secret
      namespace: monitoring

  logs-service:
    type: loki
    urlFrom: convert.nonsensitive(remote.kubernetes.secret.logs_service.data["loki-host"]) + "/loki/api/v1/push"
    auth:
      type: basic
      usernameKey: loki-username
      passwordKey: access-token
    secret:
      create: false
      name: my-monitoring-secret
      namespace: monitoring

  traces-service:
    type: otlp
    urlFrom: convert.nonsensitive(remote.kubernetes.secret.traces_service.data["tempo-host"])
    auth:
      type: bearerToken
      bearerTokenKey: tempoBearerToken
    secret:
      create: false
      name: my-tempo-secret
      namespace: tempo
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    jaeger:
      grpc:
        enabled: true

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics

podLogs:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]
    remoteConfig:
      enabled: true
      urlFrom: convert.nonsensitive(remote.kubernetes.secret.alloy_metrics_remote_cfg.data["fleet-management-host"])
      auth:
        type: basic
        usernameKey: fleet-management-user
        passwordKey: access-token
      secret:
        create: false
        name: my-monitoring-secret
  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
    alloy:
      extraEnv:
        - name: LOKI_BEARER_TOKEN
          value: sample-bearer-token
  alloy-receiver:
    presets: [deployment]
