---
global:
  # -- Override the namespace for namespaced resources created by this chart.
  # @section -- Global Settings
  namespaceOverride: ""

# -- Port number on which the server listens for new connections.
# @section -- Listener Configuration
port: 3500

# -- Whether to use the timestamp from the incoming request as the log timestamp.
# When disabled, the time the log was received is used.
# @section -- Listener Configuration
useIncomingTimestamp: false

# -- Labels to add to all received log entries.
# @section -- Listener Configuration
labels: {}

# -- Rule blocks to be added to the loki.relabel component for received logs.
# These relabeling rules are applied to logs received by this feature.
# ([docs](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.relabel/#rule))
# @section -- Log Processing
logProcessingRules: ""
