---
cluster:
  name: pod-logs-objects-cluster

destinations:
  loki:
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push
    tenantId: "1"
    auth:
      type: basic
      username: loki
      password: lokipassword

podLogsObjects:
  enabled: true
  collector: alloy-logs
  nodeFilter: true

collectors:
  alloy-logs:
    liveDebugging:
      enabled: true
    alloy:
      clustering:
        enabled: true
