---
cluster:
  name: cluster-metrics-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
  loki:
    type: loki
    url: http://loki.loki.svc:3100/api/push

# Features
clusterEvents:
  enabled: true
  collector: alloy-singleton

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  controlPlane:
    enabled: true

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

integrations:
  collector: alloy-metrics
  etcd:
    instances:
      - name: k8s-controlplane-etcd
        labelSelectors:
          app.kubernetes.io/component: etcd

# Collectors
collectors:
  alloy-metrics:
    presets: [clustered, statefulset]

  alloy-logs:
    presets: [filesystem-log-reader, daemonset]

  alloy-singleton:
    presets: [singleton]

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
