---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring-application
  namespace: argocd
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - Retry=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  source:
    repoURL: https://github.com/grafana/k8s-monitoring-helm.git
    path: charts/k8s-monitoring
    targetRevision: "main"
    helm:
      releaseName: k8smon
      valuesObject:
        cluster:
          name: argocd-deployment-test
        destinations:
          localPrometheus:
            type: prometheus
            url: http://prometheus-server.prometheus.svc:9090/api/v1/write
            auth:
              type: basic
              username: promuser
              password: prometheuspassword
          localLoki:
            type: loki
            url: http://loki.loki.svc:3100/loki/api/v1/push
            tenantId: "1"
            auth:
              type: basic
              username: loki
              password: lokipassword
        clusterMetrics:
          enabled: true
          collector: alloy-metrics

        costMetrics:
          enabled: true
          collector: alloy-metrics

        hostMetrics:
          enabled: true
          collector: alloy-metrics
          linuxHosts:
            enabled: true
          windowsHosts:
            enabled: true
          energyMetrics:
            enabled: true

        clusterEvents:
          enabled: true
          collector: alloy-singleton

        podLogsViaLoki:
          enabled: true
          collector: alloy-logs
          labelsToKeep:
            - app.kubernetes.io/name
            - container
            - instance
            - job
            - level
            - namespace
            - service.name
            - service.namespace
            - deployment.environment
            - deployment.environment.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name
            - pod
          structuredMetadata:
            pod: ""

        collectors:
          alloy-metrics:
            presets: [clustered, statefulset]
          alloy-logs:
            presets: [filesystem-log-reader, daemonset]
          alloy-singleton:
            presets: [singleton]

        collectorCommon:
          alloy:
            annotations:
              argocd.argoproj.io/sync-wave: "1"

        telemetryServices:
          kube-state-metrics:
            deploy: true
          node-exporter:
            deploy: true
          windows-exporter:
            deploy: true
          kepler:
            deploy: true
          opencost:
            deploy: true
            metricsSource: localPrometheus
            annotations:
              argocd.argoproj.io/sync-wave: "1"
            opencost:
              exporter:
                defaultClusterId: argocd-deployment-test
              prometheus:
                existingSecretName: localprometheus-k8smon-k8s-monitoring
                external:
                  url: http://prometheus-server.prometheus.svc:9090
