---
- database_observability.sql_server
- loki.enrich
- loki.secretfilter
- mimir.alerts.kubernetes
- otelcol.connector.count
- otelcol.connector.signaltometrics
- otelcol.exporter.awss3
- otelcol.exporter.debug
- otelcol.exporter.faro
- otelcol.processor.deltatocumulative
- otelcol.processor.interval
- otelcol.receiver.awscloudwatch
- otelcol.receiver.awsecscontainermetrics
- otelcol.receiver.awss3
- otelcol.receiver.cloudflare
- otelcol.receiver.datadog
- otelcol.receiver.faro
- otelcol.receiver.fluentforward
- otelcol.receiver.tcplog
- otelcol.receiver.vcenter
- prometheus.enrich
- prometheus.exporter.catchpoint
- prometheus.exporter.static
- prometheus.operator.scrapeconfigs
- prometheus.write.queue
- pyroscope.enrich
