---
- otelcol.auth.google
- otelcol.exporter.file
- otelcol.exporter.syslog
- otelcol.processor.cumulativetodelta
- otelcol.receiver.filelog
- otelcol.receiver.nginx
- otelcol.receiver.splunkhec
- otelcol.receiver.syslog
- otelcol.storage.file
