---
cluster:
  name: eks-fargate-example-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

  loki:
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push

clusterMetrics:
  enabled: true
  collector: alloy-metrics

clusterEvents:
  enabled: true
  collector: alloy-singleton

podLogsViaKubernetesApi:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-metrics: {}

  alloy-singleton: {}

  alloy-logs:
    alloy:
      clustering:
        enabled: true
      mounts:
        varlog: false
        dockercontainers: false
    controller:
      replicas: 2
      type: deployment

telemetryServices:
  kube-state-metrics:
    deploy: true
