---
cluster:
  name: terraform-test

destinations:
  localPrometheus:
    type: prometheus
    auth:
      type: basic
  localLoki:
    type: loki
    auth:
      type: basic

clusterMetrics:
  enabled: true
  collector: alloy-metrics
hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true
clusterEvents:
  enabled: true
  collector: alloy-singleton
podLogs:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-metrics: {}

  alloy-singleton: {}

  alloy-logs: {}

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
