---
cluster:
  name: metric-enrichment-test-cluster

destinations:
  metric-store:
    type: prometheus
    url: http://prometheus-server.prometheus.svc:9090/api/v1/write
    metricEnrichment:
      podLabels: [color]
      namespaceLabels: [team]

clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

collectors:
  alloy-metrics:
    includeDestinations: [metric-store]
    alloy:
      stabilityLevel: experimental

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
