---
cluster:
  name: proxies-example-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.example.com/api/v1/write
    proxyURL: https://myproxy.default.svc:8080
    noProxy: settings.example.com
    proxyConnectHeader:
      "MYPROXY-HEADER": ["my-proxy-header-value"]
    tls:
      insecure_skip_verify: true

  loki:
    type: loki
    url: http://loki.example.com/loki/api/v1/push
    proxyURL: https://myproxy.default.svc:8080
    tls:
      insecure_skip_verify: true

  tempo:
    type: otlp
    protocol: grpc
    url: http://tempo.example.com:4317
    tls:
      insecure_skip_verify: true
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}

  otlpgateway:
    type: otlp
    protocol: http
    url: https://otlpgateway.example.com:4317
    proxyURL: https://myproxy.default.svc:8080
    tls:
      insecure_skip_verify: true
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}

  pyroscope:
    type: pyroscope
    url: http://pyroscope.example.com:4040
    proxyURL: https://myproxy.default.svc:8080
    tls:
      insecure_skip_verify: true

clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

costMetrics:
  enabled: true
  collector: alloy-metrics

clusterEvents:
  enabled: true
  collector: alloy-singleton

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    zipkin:
      enabled: true

podLogs:
  enabled: true
  collector: alloy-logs

profiling:
  enabled: true
  collector: alloy-profiles

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]

  alloy-singleton:
    presets: [singleton]

  alloy-logs:
    presets: [filesystem-log-reader, daemonset]

  alloy-receiver:
    alloy:
      # The following are required for the OTLP destination using the gRPC protocol.
      # They are also used for any destination that sets `proxy_from_environment=true`.
      extraEnv:
        - name: HTTPS_PROXY
          value: https://myproxy.default.svc:8080
        - name: NO_PROXY
          value: kubernetes.default.svc

  alloy-profiles: {}

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
  opencost:
    deploy: true
    metricsSource: prometheus
    opencost:
      exporter:
        defaultClusterId: proxies-example-cluster
        extraEnv:
          HTTPS_PROXY: https://myproxy.default.svc:8080
          NO_PROXY: kubernetes.default.svc
      prometheus:
        external:
          url: http://prometheus.example.com/api/v1/query
