---
cluster:
  name: profiling-cluster

destinations:
  pyroscope:
    type: pyroscope
    url: http://pyroscope.pyroscope.svc:4040

profiling:
  enabled: true
  collector: alloy-profiles

collectors:
  alloy-profiles: {}

