---
# -- The name for this no-op destination.
# @section -- General
name: ""

# -- Set to `true` to disable this destination. Disabled destinations are excluded from all telemetry data flows, which
# is useful for removing a destination that was defined in a shared or parent values file.
# @section -- General
disabled: false

# -- Drop all metrics sent to this destination.
# @section -- Metrics
metrics:
  # -- Whether this destination will accept and drop metrics.
  # @section -- Metrics
  enabled: true

# -- Drop all logs sent to this destination.
# @section -- Logs
logs:
  # -- Whether this destination will accept and drop logs.
  # @section -- Logs
  enabled: true

# -- Drop all traces sent to this destination.
# @section -- Traces
traces:
  # -- Whether this destination will accept and drop traces.
  # @section -- Traces
  enabled: true

# -- Drop all profiles sent to this destination.
# @section -- Profiles
profiles:
  # -- Whether this destination will accept and drop profiles.
  # @section -- Profiles
  enabled: true
