---
cluster:
  name: namespace-override-test

global:
  namespaceOverride: observability

destinations:
  - name: loki
    type: loki
    url: http://loki.loki.svc:3100/api/push

podLogs:
  enabled: true

alloy-logs:
  enabled: true
