---
cluster:
  name: namespace-override-test

global:
  namespaceOverride: observability

destinations:
  loki:
    type: loki
    url: http://loki.loki.svc:3100/api/push

podLogsViaLoki:
  enabled: true

collectors:
  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
