---
cluster:
  name: pod-logs-cluster

destinations:
  loki:
    type: loki
    url: http://loki.loki.svc:3100/api/push

podLogs:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-logs: {}
