---
cluster:
  name: node-logs-cluster

destinations:
  loki:
    type: loki
    url: http://loki.loki.svc:3100/api/push

nodeLogs:
  enabled: true
  collector: alloy-logs
  journal:
    units:
      - kubelet.service
      - containerd.service

collectors:
  alloy-logs:
    presets: [filesystem-log-reader, daemonset]
