---
cluster:
  name: exclude-by-namespace-cluster

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write
  loki:
    type: loki
    url: http://loki.loki.svc:3100/api/push
  tempo:
    type: otlp
    protocol: http
    url: http://tempo.tempo.svc:443/otlp
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}
  pyroscope:
    type: pyroscope
    url: http://pyroscope.pyroscope.svc:4040

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics
  excludeNamespaces: [kube-system, kube-public, confidential]

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
  metrics:
    filters:
      metric:
        - IsMatch(resource.attributes["k8s.namespace.name"], "^kube-system|kube-public|confidential$")
      logs:
        - IsMatch(resource.attributes["k8s.namespace.name"], "^kube-system|kube-public|confidential$")
      traces:
        - IsMatch(resource.attributes["k8s.namespace.name"], "^kube-system|kube-public|confidential$")
  processors:
    k8sattributes:
      filters:
        byField:
          - key: metadata.namespace
            op: not-equals
            value: kube-system
          - key: metadata.namespace
            op: not-equals
            value: kube-public
          - key: metadata.namespace
            op: not-equals
            value: confidential

autoInstrumentation:
  enabled: true
  collector: alloy-metrics
  beyla:
    config:
      data:
        discovery:
          services:
            - k8s_namespace: "*"
          exclude_services:
            - k8s_namespace: kube-system
            - k8s_namespace: kube-public
            - k8s_namespace: confidential

clusterEvents:
  enabled: true
  collector: alloy-singleton
  excludeNamespaces: [kube-system, kube-public, confidential]

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  cadvisor:
    metricsTuning:
      excludeNamespaces: [kube-system, kube-public, confidential]

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true

podLogsViaLoki:
  enabled: true
  collector: alloy-daemonset
  excludeNamespaces: [kube-system, kube-public, confidential]

profiling:
  enabled: true
  collector: alloy-daemonset
  ebpf:
    enabled: true
    excludeNamespaces: [kube-system, kube-public, confidential]
  java:
    enabled: true
    excludeNamespaces: [kube-system, kube-public, confidential]
  pprof:
    enabled: true
    excludeNamespaces: [kube-system, kube-public, confidential]

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics
  probes:
    excludeNamespaces: [kube-system, kube-public, confidential]
  podMonitors:
    excludeNamespaces: [kube-system, kube-public, confidential]
  serviceMonitors:
    excludeNamespaces: [kube-system, kube-public, confidential]

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]
  alloy-daemonset:
    presets: [privileged, filesystem-log-reader, daemonset]
  alloy-singleton:
    presets: [singleton]
  alloy-receiver:
    presets: [deployment]

telemetryServices:
  kube-state-metrics:
    deploy: true
    namespacesDenylist: [kube-system, kube-public, confidential]
  node-exporter:
    deploy: true
