{{/* Do not edit this file. It is generated by the Makefile */}}
{{- define "integrations.types" -}}
- alloy
- cert-manager
- dcgm-exporter
- etcd
- grafana
- loki
- mimir
- mysql
- tempo
{{- end -}}
