---
# -- List of namespaces to watch for events (`[]` means all namespaces)
# @section -- Gather settings
namespaces: []

# -- List of namespaces to ignore events for.
# @section -- Gather settings
excludeNamespaces: []

# -- Log format used to forward cluster events. Allowed values: `logfmt` (default), `json`.
# @section -- Gather settings
logFormat: logfmt

# -- List of event reasons to include (`[]` means allow all event reasons). e.g. `["Failed"]`
# @section -- Processing settings
includeReasons: []

# -- List of event reasons to ignore. e.g. `["Pulling", "Started"]`
# @section -- Processing settings
excludeReasons: []

# -- List of event levels to include (`[]` means allow all event levels). e.g. `["Normal", "Warning"]`
# @section -- Processing settings
includeLevels: []

# -- List of event levels to ignore. e.g. `["Normal", "Warning"]`
# @section -- Processing settings
excludeLevels: []

# -- The value for the job label.
# @section -- Processing settings
jobLabel: "integrations/kubernetes/eventhandler"

# -- Log labels to set from extracted event fields.
# Note: "level" is always set as a label for log level normalization and filtering.
# Format: `<label>: <extracted_key>`.
# Available extracted keys: `component`, `kind`, `name`, `node`, `reason`.
# @section -- Processing settings
labels:
  reason: reason

# -- The structured metadata mappings to set.
# Format: `<key>: <extracted_key>`.
# Example:
# structuredMetadata:
#   component: component
#   kind: kind
#   name: name
# @section -- Processing settings
structuredMetadata:
  name: name
  node: node

# -- Stage blocks to be added to the loki.process component for cluster events.
# ([docs](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.process/#blocks))
# This value is templated so that you can refer to other values from this file.
# @section -- Processing settings
extraLogProcessingStages: ""
