{{- range $collectorName := include "collectors.list.enabled" . | fromYamlArray }}
{{/* Save the top level object and add the collector name */}}
{{- $values := dict "Values" $.Values "Chart" $.Chart "Files" $.Files "Release" $.Release "Subcharts" $.Subcharts "Template" $.Template "Capabilities" $.Capabilities "collectorName" $collectorName }}
{{- $collectorValues := include "collector.alloy.values" $values | fromYaml }}
{{- $alloyConfig := include "collector.alloy.config" $values }}

{{/* Ensure the collector's stability level is high enough for the components in the rendered config */}}
{{- include "collectors.validate.stabilityLevel" (dict "collectorName" $collectorName "config" $alloyConfig "collectorValues" $collectorValues "Files" $.Files) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collector.alloy.fullname" $values }}
  namespace: {{ include "helper.namespace" $ }}
data:
  config.alloy: |{{ $alloyConfig | trim | nindent 4 }}
{{- end }}
