{{- range $collector := include "collectors.list.enabled" . | fromYamlArray }}
---
apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: {{ include "collector.alloy.fullname" (deepCopy $ | merge (dict "collectorName" $collector)) }}
  namespace: {{ $.Release.Namespace }}
spec: {{ include "collector.alloy.values" (deepCopy $ | merge (dict "collectorName" $collector)) | nindent 2 }}
{{- end }}
