{{- $extraObjects := .Values.extraObjects }}
{{- if kindIs "map" $extraObjects }}
{{- $extraObjects = values $extraObjects }}
{{- end }}
{{ range $extraObjects }}
---
{{ tpl (toYaml .) $ }}
{{ end }}
