{{- $collectorName := "alloy-receiver" }}
{{- $alloyValues := (index .Values $collectorName) }}
{{- $alloyDefaultValues := "collectors/alloy-values.yaml" | .Files.Get | fromYaml }}
{{- $upstreamAlloyDefaultValues := "collectors/upstream/alloy-values.yaml" | .Files.Get | fromYaml }}
{{- $collector := deepCopy $alloyValues | merge $alloyDefaultValues $upstreamAlloyDefaultValues }}
{{- if and $collector.enabled $collector.extraService.enabled -}}
{{- $name := printf "%s-%s" .Release.Name $collector.extraService.name | trunc 63 | trimSuffix "-" }}
{{- if $collector.extraService.fullname }}
  {{- $name = $collector.extraService.fullname }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "collector.alloy.labels" (deepCopy $ | merge (dict "collectorName" $collectorName)) | nindent 4 }}
    app.kubernetes.io/component: networking
  {{- with $collector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $collector.service.type }}
  {{- if $collector.service.clusterIP }}
  clusterIP: {{ $collector.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "collector.alloy.selectorLabels" (deepCopy $ | merge (dict "collectorName" $collectorName)) | nindent 4 }}
  {{- if semverCompare ">=1.26-0" .Capabilities.KubeVersion.Version }}
  internalTrafficPolicy: {{ $collector.service.internalTrafficPolicy}}
  {{- end }}
  ports:
    - name: http-metrics
      {{- if eq $collector.service.type "NodePort" }}
      nodePort: {{ $collector.service.nodePort }}
      {{- end }}
      port: {{ $collector.alloy.listenPort }}
      targetPort: {{ $collector.alloy.listenPort }}
      protocol: "TCP"
{{- range $portMap := $collector.alloy.extraPorts }}
    - name: {{ $portMap.name }}
      port: {{ $portMap.port }}
      targetPort: {{ $portMap.targetPort }}
      protocol: {{ coalesce $portMap.protocol "TCP" }}
{{- end }}
{{- end }}
