{{- range $collectorName := keys .Values.collectors | sortAlpha }}
  {{- $values := (dict "Values" $.Values "Files" $.Files "Release" $.Release "collectorName" $collectorName) }}
  {{- $collectorValues := (include "collector.alloy.values" $values | fromYaml) }}
  {{- if $collectorValues.remoteConfig.enabled }}
    {{- $remoteConfigValues := merge (dict "type" "remoteConfig" "name" (printf "%s-remote-cfg" $collectorName)) $collectorValues.remoteConfig }}
{{- if eq (include "secrets.shouldCreateKubernetesSecret" $remoteConfigValues ) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" (dict "Values" $.Values "Chart" $.Chart "Release" $.Release "object" $remoteConfigValues "name" (printf "%s-remote-cfg" $collectorName)) | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" (dict "Release" $.Release "object" $remoteConfigValues) | quote }}
type: Opaque
data:
{{- $secrets := include "secrets.list.remoteConfig" . | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $remoteConfigValues "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $remoteConfigValues "key" $secret) }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
